import React from "react";
import { motion } from "framer-motion";
import { Network, Leaf, LineChart, Database, Shield } from "lucide-react";
import NixoNode from '../assets/nixo-logo.gif'; // Using the same asset temporarily

const NixoNodePage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto relative">
      <div
        className="fixed inset-0 bg-cover bg-center bg-no-repeat opacity-40 z-[-1]"
        style={{
          backgroundImage: `url('https://raw.githubusercontent.com/stackblitz/stackblitz-images/main/nixo-space.jpg')`,
          backgroundAttachment: "fixed",
          filter: "brightness(0.3) contrast(1.2)",
        }}
      ></div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7 }}
        className="space-y-8 relative z-10"
      >
        <div className="glass-panel p-8 md:p-12 backdrop-blur-lg bg-space-black/40">
          {/* Header Section */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.7 }}
          >
            <h1 className="text-5xl md:text-6xl font-display text-white mb-4">
              Nixo <span className="text-nixo-green glow-text">Node</span>
            </h1>
            <p className="text-2xl text-gray-300 max-w-2xl">
              Own the Network. Earn from Impact.
            </p>
          </motion.div>

          {/* Main Content */}
          <div className="mt-12 grid md:grid-cols-2 gap-8">
            {/* Left Column: Image */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.4 }}
              className="flex justify-center"
            >
              <div className="relative w-48 h-48 md:w-64 md:h-64">
                <div className="absolute inset-0 rounded-full bg-nixo-green/10 animate-pulse"></div>
                <div className="absolute inset-2 rounded-full bg-nixo-green/10" style={{ animationDuration: '3s' }}></div>
                <Network className="absolute inset-0 w-full h-full text-nixo-green p-12" />
              </div>
            </motion.div>

            {/* Right Column: Description */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.5 }}
            >
              <p className="text-xl text-gray-300 leading-relaxed mb-6">
                The Nixo Node is your opportunity to step into the backbone of the Nixo ecosystem. 
                By owning a node, you help power our decentralized infrastructure and earn a share 
                of the value generated by plastic-free actions across 1,000 Nixo Tags.
              </p>
              
              <div className="flex items-center space-x-2 mb-4">
                <Network className="w-6 h-6 text-nixo-green" />
                <Database className="w-6 h-6 text-nixo-green" />
                <Shield className="w-6 h-6 text-nixo-green" />
              </div>
            </motion.div>
          </div>
          
          {/* Node Benefits Section */}
          <div className="mt-12 space-y-8">
            <div className="space-y-4">
              <div className="flex items-center space-x-3">
                <Leaf className="w-6 h-6 text-nixo-green" />
                <h2 className="text-2xl font-display text-white">
                  Node Benefits
                </h2>
              </div>
              <div className="pl-9">
                <ul className="list-disc list-inside text-gray-300 mb-4 space-y-3 text-xl">
                  <li>Price: <span className="text-nixo-green font-bold">$1,000</span></li>
                  <li>Earn 10% reward share from all scans by tags connected to your node</li>
                  <li>Access real-time reporting of activity and earnings</li>
                  <li>Generate passive income while driving environmental impact</li>
                </ul>
              </div>
            </div>
            
            {/* Why Become a Node Section */}
            <div className="space-y-4">
              <div className="flex items-center space-x-3">
                <Leaf className="w-6 h-6 text-nixo-green" />
                <h2 className="text-2xl font-display text-white">
                  Why Become a Node?
                </h2>
              </div>
              <div className="pl-9">
                <ul className="list-disc list-inside text-gray-300 mb-4 space-y-3 text-xl">
                  <li>Support the global expansion of the Nixo DePIN network</li>
                  <li>Back a purpose-driven platform aligned with ESG and carbon neutrality goals</li>
                  <li>Participate in a transparent, on-chain revenue model</li>
                </ul>
              </div>
            </div>
            
            {/* Node Economics Section */}
            <div className="space-y-4">
              <div className="flex items-center space-x-3">
                <LineChart className="w-6 h-6 text-nixo-green" />
                <h2 className="text-2xl font-display text-white">
                  Node Economics
                </h2>
              </div>
              <div className="pl-9 glass-panel p-6 bg-space-black/60">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <h3 className="text-nixo-green text-xl mb-2">Network Coverage</h3>
                    <p className="text-gray-300">Each node supports 1,000 Nixo Tags</p>
                  </div>
                  <div>
                    <h3 className="text-nixo-green text-xl mb-2">Earning Potential</h3>
                    <p className="text-gray-300">10% of all rewards generated through connected tags</p>
                  </div>
                  <div>
                    <h3 className="text-nixo-green text-xl mb-2">Scalability</h3>
                    <p className="text-gray-300">Own multiple nodes to increase your network share</p>
                  </div>
                  <div>
                    <h3 className="text-nixo-green text-xl mb-2">Token Rewards</h3>
                    <p className="text-gray-300">Receive Nixo tokens directly to your wallet</p>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Call to Action */}
            <div className="mt-8 text-center">
              <p className="text-nixo-green font-display text-2xl">
                <Leaf className="inline w-5 h-5 mr-1" /> Start earning. Start scaling.
              </p>
              <p className="text-white font-display text-xl mt-2">
                Be a Nixo Node.
              </p>
              <div className="mt-6">
                <button className="bg-nixo-green hover:bg-nixo-green-light text-white font-bold py-3 px-8 rounded-full transition-colors duration-300 shadow-glow-green">
                  Become a Node Owner
                </button>
              </div>
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default NixoNodePage;